### ISSUE TITLE
Use GAMA model min-max slider boundery

### ISSUE THREAD

**Issue by RoiArthurB** [WARMTeam/HoanKiemAir_Android#5]
As we where modifying the GAML model to fit our presentation need, we wanted to go beyond the original max number of vehicules. Unfortunatly for us, slider boundaries are hard-coded inside the app. 

It would make the app way more extensible if it could gather min/max parameter's value from the GAMA model instead of hard-coded value :)

**Comment by hu1909** [comment]
About this issue, I think I have 2 options to fix this because the min-max slider boundary must have the max value otherwise GAML model can not read and change base on that value. So

   + The first options is that I will increase the number of vehicle more higher for example 5.000 or 10.000 and I think it can be nice to show when the rate of pollution is extremely high 
   + The second option is that I will remove slide min-max and add some fix value so user can change to any value they want but It make an Android not quite beautiful like this one :)

And how do you think about 2 options @RoiArthurB

**Comment by RoiArthurB** [comment]
Go for the first option then :)

**Comment by hu1909** [comment]
Thanks you @RoiArthurB , I have changed its value
